### ISSUE TITLE
CMakeLists.txt file modification

### ISSUE THREAD

**Issue by g41903** [personalrobotics/apriltags#21]
In the CMakeList.txt file:
Change https://github.com/personalrobotics/apriltags-cpp to https://github.com/personalrobotics/apriltags-cpp.git
Then make the workspace:

For example in CMakeLists.txt:
Original file:
ExternalProject_Add(apriltags_swatbotics_EXTERNAL
    GIT_REPOSITORY https://github.com/personalrobotics/apriltags-cpp
    INSTALL_COMMAND ""
    BUILD_COMMAND "make" # I don't know why this works...
    CMAKE_ARGS -DCMAKE_CXX_FLAGS=-frounding-math -DBUILD_SHARED_LIBS:BOOL=ON
)

File after modification:
ExternalProject_Add(apriltags_swatbotics_EXTERNAL
    GIT_REPOSITORY https://github.com/personalrobotics/apriltags-cpp.git
    INSTALL_COMMAND ""
    BUILD_COMMAND "make" # I don't know why this works...
    CMAKE_ARGS -DCMAKE_CXX_FLAGS=-frounding-math -DBUILD_SHARED_LIBS:BOOL=ON
)

**Comment by psigen** [comment]
Can you propose this as a pull request?  GitHub will do this for you automatically if you click `Edit` on this file in the web browser and type in your changes.
